# Generated by Django 5.0 on 2024-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
