# Generated by Django 5.0.1 on 2024-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='similarity_rating',
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
